# Generated by Django 5.0 on 2023-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='dob',
            field=models.DateField(),
        ),
    ]
