# Generated by Django 5.0 on 2023-12-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_turf_images_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('card_balance', models.IntegerField(default=1000000)),
                ('expiration_date', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.login')),
            ],
        ),
    ]
