# Generated by Django 5.0 on 2023-12-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turf',
            name='price_per_slot',
            field=models.IntegerField(),
        ),
    ]
