# Generated by Django 5.0 on 2024-01-03 09:34

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_alter_payment_amount_alter_turf_price_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager')], default='user', max_length=30),
        ),
    ]
