# Generated by Django 5.0 on 2024-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0006_slot_date_alter_login_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
