# Generated by Django 5.0 on 2024-01-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0007_alter_slot_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
