# Generated by Django 5.0 on 2024-01-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0008_remove_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='duration_per_slot',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
