# Generated by Django 5.0 on 2024-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0009_turf_duration_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
